### PR TITLE
add support for tiled images

### LINKED ISSUE #104: TiffImages fails to open Tiled TIFFs
It's more related to performance rather than inability to read I think but here the error seems slightly when I try it without FileIO and in a isolated env. When I used with FileIO, error was different as seen here:https://github.com/JuliaImages/ImageSegmentation.jl/issues/94#issuecomment-1539264905
Noticed here: https://github.com/JuliaImages/ImageSegmentation.jl/issues/94 as the OP wanted to load a very large 30k*10k image which is here: https://github.com/niccolo99mandelli/JHistint.jl/blob/main/output_example/SlideExample.tif

MWE:
```
julia> using TiffImages
[ Info: Precompiling TiffImages [731e570b-9d59-4bfa-96dc-6df516fadf69]

julia> img = TiffImages.load("SlideExample.tif")
ERROR: KeyError: key 0x0111 not found
Stacktrace:
  [1] getindex
    @ C:\Users\lenono\.julia\packages\OrderedCollections\vTcqn\src\ordered_dict.jl:385 [inlined]
  [2] getindex
    @ C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\ifds.jl:31 [inlined]
  [3] getindex
    @ C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\ifds.jl:30 [inlined]
  [4] read!(target::Matrix{ColorTypes.RGB{FixedPointNumbers.N0f8}}, tf::TiffFile{UInt32, FileIO.Stream{FileIO.DataFormat{:TIFF}, IOStream, String}}, ifd::TiffImages.IFD{UInt32})
    @ TiffImages C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\ifds.jl:118
  [5] macro expansion
    @ C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:63 [inlined]
  [6] macro expansion
    @ C:\Users\lenono\.julia\packages\ProgressMeter\sN2xr\src\ProgressMeter.jl:938 [inlined]
  [7] load(tf::TiffFile{UInt32, FileIO.Stream{FileIO.DataFormat{:TIFF}, IOStream, String}}, ifds::Vector{TiffImages.IFD{UInt32}}, N::Int64; verbose::Bool)
    @ TiffImages C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:62
  [8] load(tf::TiffFile{UInt32, FileIO.Stream{FileIO.DataFormat{:TIFF}, IOStream, String}}; verbose::Bool, mmap::Bool)
    @ TiffImages C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:24
  [9] load(io::IOStream; verbose::Bool, mmap::Bool)
    @ TiffImages C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:7
 [10] #8
    @ C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:3 [inlined]
 [11] open(f::TiffImages.var"#8#9"{Bool, Bool}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\io.jl:384
 [12] open
    @ .\io.jl:381 [inlined]
 [13] #load#7
    @ C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:2 [inlined]
 [14] load(filepath::String)
    @ TiffImages C:\Users\lenono\.julia\packages\TiffImages\lJfX2\src\load.jl:1
 [15] top-level scope
    @ REPL[4]:1

```

### PR DESCRIPTION
**Pull request by chrstphrbrns**
Fixes #104

### CODE REVIEW

**Review by tlnagy — APPROVED** [review]
This looks great! Super clean implementation.

**Comment by tlnagy** [comment]
Do you mind dropping the version number to v0.7.1? I know VersionVigilante will complain, but I rather this with #122 in one release. 

Technically since this is a major feature update this would've made more sense to include in a minor release (i.e. `v0.8.0`) instead of a patch release. Honestly, with your contributions here and with #116, `TiffImages.jl` is rapidly approaching what I would consider sufficient for a first 1.0 release. 

Are you planning on tackling any other major PRs soon? Because we could stack them and release them all as TiffImages v1.0.0.

Thanks for all your hard work!

**Comment by chrstphrbrns** [comment]
I have PRs for #119, #58, and support for "planar" images

**Comment by tlnagy** [comment]
Perfect! I'll release v0.7.1 as a patch release and then we can batch all of those PRs as v0.8.0

**Review by tlnagy — APPROVED** [review]

**Comment by chrstphrbrns** [comment]
For 1.0, I think it makes sense to try supporting most if not all of the [LibTIFF test images](http://www.simplesystems.org/libtiff/images.html) (JPEG might be a tall order)

**Pull request merged**
