### PR TITLE
add support for planar images

### LINKED ISSUE #125: Add support for "planar" images
Add support for images with [PLANARCONFIG](https://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html) = PLANARCONFIG_SEPARATE

### PR DESCRIPTION
**Pull request by chrstphrbrns**
Fixes #125

### CODE REVIEW

**Comment by chrstphrbrns** [comment]
For one particular 5120x2880 image, it's roughly 130ms vs 80ms (results are similar for compressed and uncompressed versions of the image)

**Comment by tlnagy** [comment]
I hacked up a quick script to 

<details>
  <summary>Script</summary>

  ```julia
  module TestMain
      println(@__MODULE__)
      using Pkg
      Pkg.activate(; temp = true)
      Pkg.add("TiffImages")

      a = @elapsed Base.compilecache(Base.identify_package("TiffImages"))

      b = @elapsed using TiffImages

      open("timings.txt", "w") do f
          write(f, join([string(@__MODULE__), a, b], "\t"), "\n")
      end
  end

  module TestPR136
      println(@__MODULE__)

      using Pkg
      Pkg.activate(; temp = true)
      Pkg.develop("TiffImages")

      a = @elapsed Base.compilecache(Base.identify_package("TiffImages"))

      b = @elapsed using TiffImages

      open("timings.txt", "a") do f
          write(f, join([string(@__MODULE__), a, b], "\t"), "\n")
      end
  end
  ```
</details>

Which gave the following: 

| Condition      | Precompilation (s) | Using (s)   | Using Delta (%) |
|----------------|--------------------|-------------|-------|
| Main.TestMain  | 38.981615158       | 0.869952215 | 1.0   |
| Main.TestPR136 | 39.184539139       | 1.031776947 | 1.19  |

So this PR results in approximately the same precompilation time, but almost 20% reduction in speed when loading.

**Comment by chrstphrbrns** [comment]
For me, a 40% per-image win easily justifies an imperceptible (or barely perceptible) increase in one-time load cost

FWIW, the PR for #58 also has a SIMD path, which gives somewhat better improvements for "unusual" bit depths

Twice as fast is nothing to sneeze at

**Comment by tlnagy** [comment]
The SIMD path would only accelerate the speed of loading planar images, no? The 20% increase in speed hits everyone, while the increase in speed would only benefit folks loading the planar images (which is likely a small subset of folks). I'm not totally against including SIMD as a dependency, I just want to make sure that it's justified.

**Comment by chrstphrbrns** [comment]
The additional delay is fixed and imperceptible, so I round it down to zero, whereas the optimization is per-image and the benefits therefore unbounded. One might argue that few will process enough images to appreciate the benefits, but then, again, the cost is ~zero

Do you prefer to keep the code simple for now and defer optimization until later?

**Comment by tlnagy** [comment]
Sorry for the delay with this, but I decided that the delay (particularly with the advances in Julia v1.10 on that front) should be fine. I think it likely makes sense to let this stew on `main` for a bit and then tag `v0.9` to release it.

**Pull request merged**
