### PR TITLE
parallelize decoding

### LINKED ISSUE #119: Parallelize decoding
Parallelizing decoding is straight-forward with TIFFs since they are composed of separately-encoded strips or tiles

One might say this should be done at the client/file level, but for large files it may be convenient to have it done at the strip level, especially in an interactive context

Here are results I get for a variety of LZW-compressed images--from tiny to huge, for white noise and solid color--showing a win for all but the smallest, simplest images

**white noise**
| serial (s)     | parallel (s)   |
|----------------|----------------|
| 25.06848       | 3.21034        |
| 2.06287        | 0.30021        |
| 0.27048        | 0.07222        |
| 0.06873        | 0.02438        |
| 0.00174        | 0.00331        |

**solid color**
| serial (s)     | parallel (s)   |
|----------------|----------------|
| 1.35969        | 0.88756        |
| 0.08941        | 0.05104        |
| 0.00777        | 0.01789        |
| 0.00193        | 0.00331        |
| 0.00012        | 0.00023        |

### PR DESCRIPTION
**Pull request by chrstphrbrns**
Fixes #119

### CODE REVIEW

**Review by tlnagy — APPROVED** [review]

**Comment by tlnagy** [comment]
Thanks for the PR! Is there an easy way we could test the parallelism? I'm a little leery of releasing it without tests, but I understand if there isn't an easy way to do so.

**Comment by chrstphrbrns** [comment]
Parallelism is enabled by default, so it depends on how the test container is configured. Would you prefer to disable parallelism by default?

**Comment by tlnagy** [comment]
It would be nice to test both branches ideally. Not sure if that's possible with the current architecture.

**Comment by chrstphrbrns** [comment]
If the tests aren't being run with multiple threads, then verifying that it's using both branches would be tricky

**Comment by tlnagy** [comment]
Do you mind rebasing this PR too?

**Comment by tlnagy** [comment]
@chrstphrbrns This PR needs a rebase to be merged. Thanks!

**Comment by chrstphrbrns** [comment]
Waiting on #130

**Comment by tlnagy** [comment]
Ah, my bad. #130 is now merged.

**Comment by tlnagy** [comment]
Thanks for this PR @chrstphrbrns! :rocket:

I think with this PR merged, I'm ready to tag `v0.8.0` and release this into the wild.

**Pull request merged**
