### PR TITLE
Add precompile helper

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by timholy** [comment]
Let's hold off on this for a second; I took a quickly look myself, and it seems there are quite a few inference problems that can be fixed. Once you [eat dessert it's actually harder to eat your vegetables](https://timholy.github.io/SnoopCompile.jl/stable/snoopi_deep_parcel/#Using-@snoopi_deep-results-to-generate-precompile-directives) because the caching masks triggers of inference.

**Comment by IanButterworth** [comment]
@timholy Small thought.. The timings in the precompile directives file are nice, but frustratingly break git diffs, so it's harder to tell what changes

**Comment by timholy** [comment]
One point: you could conceivably just use `precomp_gen.jl` as the precompiler. Yes, you'd be creating actual objects when the package gets compiled, but that's not the worst thing in the world, and it is shorter. Check out the precompile file in https://github.com/JuliaImages/ImageCore.jl/pull/157. You would have to return something so that the compiler doesn't decide to elide all the precompilation code, but that shouldn't be too hard.

Another one: if you do keep the explicit `precompile` directives, I almost always put an `@assert` in front of them now so I know when they go stale.

**Comment by IanButterworth** [comment]
I'm a bit confused as to why codecov is reporting a reduction here, but should be good to merge @tlnagy

**Comment by IanButterworth** [comment]
Oh.. right, codecov is being run on both 1.5 and nightly. So on one the precompiles are being skipped

**Comment by tlnagy** [comment]
This looks good to me. Why are the precompiles only included for 1.6-dev+?

**Comment by IanButterworth** [comment]
I was being lazy and hadn't checked that they pass for 1.5. Just updated. If you want to check that they work for older versions, feel free to update or merge (once the CI re-runs)

**Comment by IanButterworth** [comment]
> Also will I need to rerun this on every release?

That is one of the down-sides of `precompile` directives over just running some code, which @timholy was advocating for above. I didn't go that way because `snooping.jl` uses the whole test suite to generate precompile directives, so should have better coverage than that just in `precomp_gen.jl`. If you think that's enough, then we could just run that code during precomp instead.

**Comment by timholy** [comment]
FYI I've not noticed downsides to precompiling for any version after 1.4.2, as long as they are the same precompiles. But before 1.4.2 you can trigger segfaults by precompiling so it's better to be safe.

**Comment by tlnagy** [comment]
> > Also will I need to rerun this on every release?
> 
> If you think that's enough, then we could just run that code during precomp instead.

I think I would prefer that. I know myself and I'll struggle to remember to rebuild the precompilation signatures regularly.

Could you also add `N0f16` and `Float32` to the type list? I think that should cover common use cases.

**Comment by IanButterworth** [comment]
Great, yeah that simplifies this then. I also added `GrayA` and `RGBA`.

This PR should be squash merged. I didn't rebase squash in case anyone wants to review the intermediate snoop scripts in the future.

@timholy looks like FileIO is hitting a precompile directive error on nightly on != ubuntu
```
ERROR: LoadError: AssertionError: precompile(f, (Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(load), String))
Stacktrace:
 [1] _precompile_()
   @ FileIO ~/.julia/packages/FileIO/C7O10/src/precompile.jl:52
```

**Comment by timholy** [comment]
> looks like FileIO is hitting a precompile directive error on nightly on != ubuntu

That will be fixed when https://github.com/JuliaIO/FileIO.jl/pull/295 merges. Should I go ahead and do that or wait longer? From my standpoint it's ready.

**Comment by IanButterworth** [comment]
I just commented. Sorry, not had time to give the diff a proper review, but from my perspective I see no reason to not go ahead if you consider it ready

**Comment by tlnagy** [comment]
Can I go ahead and merge this? Little confused by the linked issue.

**Comment by IanButterworth** [comment]
It should be safe to merge, but you might want to re-run CI to check?

**Comment by IanButterworth** [comment]
If we can merge this, can we get out a new release and merge the FileIO Tiff update? 

(On my phone, hence the lack of PR links)

**Pull request merged**
